### ISSUE TITLE
The function ycGetPolygonArea is not working.

### ISSUE THREAD

**Issue by SwashbucklerPup** [yeungchie/virtuoso-geometry#1]
1.The initial value of the variable 'i' should be set to 1; otherwise, the variables 'a' and 'b' will always be the same.

2.When using 'area += xCoord(a) * yCoord(b) - yCoord(a) * xCoord(b)', parentheses should be added around the two polynomials being subtracted.

3.The modified code is as follows：

procedure(ycGetPolygonArea(points "l")
    let((i(i) b area(0))
        foreach(a points
            unless(isLocation(a)
                ycError("arguments #1 is not a valid point list - %A" a)
            )
            b = nth(i points) || car(points)
            area += (xCoord(a)*yCoord(b) - yCoord(a)*xCoord(b))
            i++
        )
        abs(area)/2
     )
); ycGetPolygonArea

**Comment by yeungchie** [comment]
1. Original calculation process was incorrect and has been corrected. Code logic is more concise.
2. Expression syntax has been corrected.

```lisp
ycGetPolygonArea('((2 2) (1 2) (0 1) (0 0) (2 0)))
; => 3.5
```
